customers:
  ARGALYS:
    transform: raw         # or log1p
    models:
      - name: ARIMA
        family: arima
        grid:
          p: [0,1,2]
          d: [0,1]
          q: [0,1,2]
      - name: ETS-Add
        family: ets
        params: {trend: "add", seasonal: "add", sp: 7}
      - name: LGBM
        family: gbm
        params:
          learning_rate: 0.1
          max_depth: 5
          n_estimators: 300
          subsample: 0.9
          colsample_bytree: 0.9
        use_lightgbm: true

  LES MIRACULEUX:
    transform: log1p
    models:
      - name: SARIMA_111_111_12
        family: sarima
        params: {p:1,d:1,q:1,P:1,D:1,Q:1,sp:12}
      - name: ProphetMul
        family: prophet
        params: {seasonality_mode: "multiplicative", changepoint_prior_scale: 0.5}
      - name: LGBM
        family: gbm
        params:
          learning_rate: 0.1
          max_depth: 6
          n_estimators: 400
          subsample: 0.9
          colsample_bytree: 0.9
        use_lightgbm: true

  MINCI DELICE:
    transform: log1p
    models:
      - name: ETS-Mul
        family: ets
        params: {trend: "mul", seasonal: "mul", sp: 7}
      - name: SARIMA_weekly
        family: sarima
        params: {p:1,d:0,q:1,P:1,D:1,Q:1,sp:7}
      - name: ProphetMul
        family: prophet
        params: {seasonality_mode: "multiplicative", changepoint_prior_scale: 0.1}

  NUTRAVANCE:
    transform: log1p
    models:
      - name: ETS-Add
        family: ets
        params: {trend: "add", seasonal: "add", sp: 7}
      - name: SARIMA_101_111_7
        family: sarima
        params: {p:1,d:0,q:1,P:1,D:1,Q:1,sp:7}
      - name: LGBM
        family: gbm
        params:
          learning_rate: 0.1
          max_depth: 5
          n_estimators: 350
          subsample: 0.9
          colsample_bytree: 0.9
        use_lightgbm: true